### ISSUE TITLE
Phoenix - Organising your code (Gareth Townsend)

### ISSUE THREAD

**Issue by quamen** [elixir-melbourne/meetup#13]
Based on insights from Chris McCord's ElixirConf keynote. Learn how to structure your Phoenix code base for long term maintain ability and an easy migration to Phoenix 1.3

**Comment by rakr** [comment]
I would suggest using this deck as a reference, this was a great talk at elixirconf 2016: [Building an Umbrella Project](https://speakerdeck.com/wojtekmach/building-an-umbrella-project)
