### ISSUE TITLE
Phoenix - Controllers (Alan Harper)

### ISSUE THREAD

**Issue by madlep** [elixir-melbourne/meetup#18]
http://www.phoenixframework.org/docs/controllers

**Comment by aussiegeek** [comment]
Feel like my Plug talk as wandered off in to controller territory. Can either trim back a little to leave this for someone, or go a bit further and touch on it a bit me

**Comment by madlep** [comment]
@aussiegeek all good if you want to go further and do a plug/controller combined talk. Can stretch out the time as well if you want past 10 mins

**Comment by madlep** [comment]
This talk maybe combined with https://github.com/elixir-melbourne/meetup/issues/12 and maybe longer than 10 minutes all up. Up to @aussiegeek
