### ISSUE TITLE
Gareth Townsend - An introduction to OTP supervision trees

### ISSUE THREAD

**Issue by quamen** [elixir-melbourne/meetup#2]
A basic concept in Erlang/OTP is the supervision tree. This is a process structuring model based on the idea of workers and supervisors:
- Workers are processes that perform computations, that is, they do the actual work.
- Supervisors are processes that monitor the behaviour of workers. A supervisor can restart a worker if something goes wrong.
- The supervision tree is a hierarchical arrangement of code into supervisors and workers, which makes it possible to design and program fault-tolerant software.

**Comment by madlep** [comment]
@quamen looks great. I guessed at 20min talk at beginner level. Feel free to change around labels if that's not right.
