### ISSUE TITLE
Multiplayer games with Phoenix Channels (David Cristofaro)

### ISSUE THREAD

**Issue by madlep** [elixir-melbourne/meetup#24]
From message David sent on meetup

> You mentioned it would be great if someone spoke about Phoenix Channels next month. A couple of months ago I build a really simple multiplayer game using Phoenix Channels. I'd be happy to give a tutorial of channels by showing the source of my little game. It will be interactive, fun and I think people would like it. 
> 
> https://github.com/dtcristo/tap-racer 
> 
> Give it a play. Instructions are on the repo.

**Comment by dtcristo** [comment]
I'm excited for this.

Things I need to do before the meetup:
- [x] Cleanup code so it's simpler and more idiomatic Elixir.
- [x] Read up on the docs for Channels so I'm up to date.
- [x] Work on an outline for the talk. Something like: Interactive demo, Channels overview, Dive into code, Questions.
- [x] Make the game better and more fun.

I'm thinking the whole talk and demo will be around 20 minutes.

**Comment by madlep** [comment]
Hey @dtcristo. Just checking in you're still good for Wednesday?

**Comment by dtcristo** [comment]
Thanks @madlep. Still good for Wednesday. I've been working on some [notes](https://github.com/dtcristo/tap-racer/blob/master/NOTES.md). Still a work in progress but will be ready for Wednesday.
