### ISSUE TITLE
Volunteer for talks at November meetup

### ISSUE THREAD

**Issue by elliotthilaire** [elixir-melbourne/meetup#29]
Hello,

I'll be a visitor at the November meetup. I'd be happy to do a talk if there's a slot.
Since I don't know about the format, or what the regular attendees prefer, here are some options for you to consider.

---

**User Defined GraphQL API's with Absinthe
or; How to Compile Elixir Code at Runtime**
I started to build a CMS as a Service using GraphQL. I ran problems when I found out Absinthe schema definitions use macros, which are expanded at compile time, which make it difficult to dynamically define them. In this talk I share what I learned about meta-programming and some nifty functions Elixir provides to generate and compile code at runtime. Is compiling code at runtime genius or utterly terrifying? That's for the audience to decide.

This talk is best suited to people who have some knowledge of Absinthe (since there was a talk about it at the last meetup maybe this won't be a problem?). The stuff learned can be applied to other contexts too.

Talk time: maybe 30 minutes

---

**Organising Tests in ExUnit for Project Growth**
This talk covers the strengths and weaknesses I discovered in ExUnit after coming from RSpec/Minitest. I talk about the implications of only being able to nest describe blocks one level deep (different to RSpec). I show how I arrange tests so that I don't have to reorganize them them when I add new features and behaviour. I explain what the ExUnit 'context' is and dig a little bit into how ExUnit works.

This is beginner friendly talk best suited for someone who has written an ExUnit test or two before but doesn't yet know all the ins and outs.

Talk time: maybe 20 minutes

---

**Multiplayer Sheep Simulator Demo**
A quick interactive demo and tour of a game/toy that uses Phoenix channels and the Phaser (JavaScript) game library.

Talk time: maybe 10 minutes

---

### About me
I used to live in Brisbane. Then I moved to the UK and worked at Square Enix—the company behind games such as Final Fantasy and Tomb Raider—where I wrote a lot of Elixir. 
I became a regular at the London Elixir meetup and enjoyed attending the Elixir conferences across Europe. 
I lived in the UK for two years. Now I am back in Australia and am keen to share what I have learned.

**Comment by elliotthilaire** [comment]
Hello @madlep, 

Could you please let me know if you're interested in one of these so that I can prepare.

Thanks, 

Elliott

**Comment by madlep** [comment]
Hey @elliotthilaire. The Absinthe talk looks great. There's usual a lot of interest in using GraphQL, so that would be a popular topic.

Usually we have 2x 20-30 minute talks in the evening. Typically we the audience tends to skew toward beginner, but there is a good range of experience levels there. I'd assume that everyone in the audience has good programming experience, some Elixir, but probably not expert at it.

Also, apologies for the delay in responding :)

**Comment by elliotthilaire** [comment]
Thanks @madlep. Sign me up. I’ll do the absinthe talk.

**Comment by elliotthilaire** [comment]
Thanks for having me!
