### ISSUE TITLE
Gareth Townsend - Using GenEvent

### ISSUE THREAD

**Issue by quamen** [elixir-melbourne/meetup#6]
GenEvent is an OTP behaviour module for implementing event handling functionality.

From the docs:

> There are many use cases for event handlers. For example, a logging system can be built using event handlers where each log message is an event and different event handlers can be plugged to handle the log messages. One handler may print error messages on the terminal, another can write it to a file, while a third one can keep the messages in memory (like a buffer) until they are read.

This talk will walk you through how to set up and use GenEvent within an OTP application.

Time: 20min
Skill Level: Intermediate

**Comment by madlep** [comment]
Awesome! Looking forward to it
