### ISSUE TITLE
Patrick - Macros In Action

### ISSUE THREAD

**Issue by patrobinson** [elixir-melbourne/meetup#8]
I'll be talking about how Macros are implemented in Elixir (and how they differ from the Erlang implementation). How Macros are used as the foundation that Elixir is built on top of. Then we'll delve into some examples (likely how Plug implements them) and how to troubleshoot them (line numbers are no help when tracing errors).

time for session 20min
target skill level intermediate

**Comment by madlep** [comment]
@patrobinson I'll schedule this talk for next month's meetup, as we'll be full with lightning talks + one 20 minute talk already. Let me know if that doesn't work for you!
